version: '3.8'

services:
  database:
    image: postgres:latest
    env_file:
      - ./database/.env
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: testroot
    networks:
      - database-backend

  backend-dev:
    build:
      context: ./backend
    env_file:
      - ./backend/dev.env
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
    depends_on:
      - database
    networks:
      - database-backend

  backend-prod:
    build:
      context: ./backend
    env_file:
      - ./backend/prod.env
    ports:
      - "4000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4000"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
    depends_on:
      - database
    networks:
      - database-backend

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    ports:
      - "5173:5173"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    ports:
      - "5000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  database-backend:
    driver: overlay
