version: '3.8'

services:
  database:
    image: milan98080/todo-database:latest
    env_file:
      - ./database/.env
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: testroot
    networks:
      - database-backend

  backend-dev:
    image: milan98080/todo-backend-dev:latest
    env_file:
      - ./backend/dev.env
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - database
    networks:
      - database-backend

  backend-prod:
    image: milan98080/todo-backend-prod:latest
    env_file:
      - ./backend/prod.env
    ports:
      - "4000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - database
    networks:
      - database-backend

  frontend-dev:
    image: milan98080/todo-frontend-dev:latest
    ports:
      - "5173:5173"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend-prod:
    image: milan98080/todo-frontend-prod:latest
    ports:
      - "5000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  database-backend:
    driver: overlay
