version: '3.8'

services:
  database:
    container_name: database-container
    image: postgres:latest
    env_file:
      - ./database/.env
    networks:
      - database-backend
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: testroot
    restart: always

  backend-dev:
    container_name: backend-container-dev
    build:
      context: ./backend
    env_file:
      - ./backend/dev.env
    ports:
      - "3000:3000"
    networks:
      - database-backend
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
    restart: always

  backend-prod:
    container_name: backend-container-prod
    build:
      context: ./backend
    env_file:
      - ./backend/prod.env
    ports:
      - "4000:3000"
    networks:
      - database-backend
    depends_on:
      - database
    restart: always

  frontend-dev:
    container_name: frontend-container-dev
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    restart: always

  frontend-prod:
    container_name: frontend-container-prod
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    ports:
      - "5000:80"
    restart: always

networks:
  database-backend:
    driver: bridge
