name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

env:
  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

jobs:
  build-and-push-main:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # Adjust version if needed

      - name: Set Git Config
        run: |
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image for Main
        run: |
          cd backend
          docker build -t ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:main .
          docker tag ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:main ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:main-$(git rev-parse --short HEAD)

      - name: Push Docker Image for Main
        run: |
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:main
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:main-$(git rev-parse --short HEAD)

  build-and-push-dev:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # Adjust version if needed

      - name: Set Git Config
        run: |
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image for Dev
        run: |
          cd backend
          docker build -t ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:dev .
          docker tag ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:dev ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:dev-$(git rev-parse --short HEAD)

      - name: Push Docker Image for Dev
        run: |
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:dev
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:dev-$(git rev-parse --short HEAD)

  bump-version:
    runs-on: self-hosted
    needs: [build-and-push-main, build-and-push-dev]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Git Config
        run: |
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"

      - name: Bump Version
        run: |
          cd backend
          npm version patch
          cd ..
          git add .
          git commit -m "[skip ci] Bump version"
          git push --follow-tags
