name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

env:
  GITHUB_EMAIL: $GIT_EMAIL
  GITHUB_USERNAME: $GIT_USERNAME

jobs:
  build-and-push:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Determine Branch
        id: determine_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set Git Config
        run: |
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"

      - name: Login to Docker Hub
        run: echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t "${REPOSITORY}/${IMAGE_NAME}:${{ steps.determine_branch.outputs.branch }}" .

      - name: Tag Docker Image
        run: |
          docker tag "${REPOSITORY}/${IMAGE_NAME}:${{ steps.determine_branch.outputs.branch }}" "${REPOSITORY}/${IMAGE_NAME}:${{ steps.determine_branch.outputs.branch }}-$(git rev-parse --short HEAD)"

      - name: Push Docker Image
        run: |
          docker push "${REPOSITORY}/${IMAGE_NAME}:${{ steps.determine_branch.outputs.branch }}"
          docker push "${REPOSITORY}/${IMAGE_NAME}:${{ steps.determine_branch.outputs.branch }}-$(git rev-parse --short HEAD)"

      - name: Bump Version
        if: ${{ steps.determine_branch.outputs.branch == 'main' }}
        run: |
          cd backend
          npm version patch
          cd ..
          git add .
          git commit -m "[skip ci] Bump version"
          git push --follow-tags
