name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

env:
  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Determine Branch and Set Output Name
        id: determine_branch
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          if [ "$branch" = "main" ]; then
            echo "::set-output name=name::prod"
          else
            echo "::set-output name=name::${branch}"
          fi

      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set Git Config
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_USERNAME}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ steps.determine_branch.outputs.branch }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ steps.determine_branch.outputs.branch }} ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ steps.determine_branch.outputs.branch }}-$(git rev-parse --short HEAD)

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ steps.determine_branch.outputs.branch }}
          docker push ${{ secrets.REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ steps.determine_branch.outputs.branch }}-$(git rev-parse --short HEAD)

      - name: Bump Version
        if: ${{ steps.determine_branch.outputs.branch == 'dev' }}
        run: |
          cd backend
          npm version patch
          cd ..
          git add .
          git commit -m "[skip ci] Bump version"
          git push --follow-tags
